include: package:lints/recommended.yaml

analyzer:
  exclude:
    - test/**/fixtures/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    include:
      - avoid_types_on_closure_parameters
      - prefer_void_to_null
      - void_checks
    exclude:
      - overridden_fields
