include: package:pedantic/analysis_options.1.8.0.yaml

analyzer:
  exclude:
    - test/tools/fixtures/**
    # Tests that depend on globally activating a package create a separate,
    # temporary pub cache directory that needs to be excluded from analysis to
    # prevent its files from showing up in an IDE analysis pane.
    - test_pub_cache**
  language:
    strict-inference: true
    strict-raw-types: true
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

linter:
  rules:
    - avoid_types_on_closure_parameters
    - prefer_void_to_null
    - void_checks
