include: package:lints/recommended.yaml

analyzer:
  exclude:
    - test/**/fixtures/**
  language:
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    avoid_types_on_closure_parameters: true
    prefer_void_to_null: true
    void_checks: true
