@TestOn('vm')
library test.unit.vm.generated_runner;

// Generated by `pub run dart_dev gen-test-runner -d test/unit/vm -e Environment.vm --no-genHtml`

import './checked_mode_test.dart' as checked_mode_test;
import 'package:test/test.dart';

void main() {
  checked_mode_test.main();
}