@TestOn('browser')
library test.generated_runner;

// Generated by `pub run dart_dev gen-test-runner -d test/ -e Environment.browser --no-genHtml`

import './browser_test.dart' as browser_test;
import 'package:test/test.dart';

void main() {
  browser_test.main();
}