@TestOn('browser')
library test.generated_runner;

// Generated by `pub run dart_dev gen-test-runner -d test/ -e Environment.browser --genHtml`

import 'package:test/test.dart';
import './browser_test.dart' as browser_test;

void main() {
  browser_test.main();
}