@TestOn('browser')
library test.unit.browser.generated_runner;

// Generated by `pub run dart_dev gen-test-runner -d test/unit/browser -e Environment.browser --no-genHtml`

import './checked_mode_test.dart' as checked_mode_test;
import 'package:test/test.dart';

void main() {
  checked_mode_test.main();
}