name: CI

on: [push]

jobs:
  analyze:
    name: Analyze
    strategy:
      fail-fast: false
      matrix:
        dart: ["2.3", "latest", "dev"]
    runs-on: ubuntu-latest
    container: google/dart:${{ matrix.dart }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: pub get --no-precompile
      - run: pub run dart_dev analyze

  format:
    name: Format
    strategy:
      fail-fast: false
      matrix:
        dart: ["2.3", "latest", "dev"]
    runs-on: ubuntu-latest
    container: google/dart:${{ matrix.dart }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: pub get --no-precompile
      - run: pub run dart_dev format --check

  publish-dry-run:
    name: Publish Dry-Run
    strategy:
      fail-fast: false
      matrix:
        dart: ["2.3", "latest", "dev"]
    runs-on: ubuntu-latest
    container: google/dart:${{ matrix.dart }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: pub get --no-precompile
      - run: pub publish --dry-run

  validate-deps:
    name: Validate Deps
    strategy:
      fail-fast: false
      matrix:
        dart: ["2.3", "latest", "dev"]
    runs-on: ubuntu-latest
    container: google/dart:${{ matrix.dart }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: pub get --no-precompile
      - run: pub run dependency_validator -i pedantic

  test1:
    name: Test (1/5)
    strategy:
      fail-fast: false
      matrix:
        dart: ["2.3", "latest", "dev"]
    runs-on: ubuntu-latest
    container: google/dart:${{ matrix.dart }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: pub get --no-precompile
      - run: pub run dart_dev test --test-args="--shard-index=0 --total-shards=5"

  test2:
    name: Test (2/5)
    strategy:
      fail-fast: false
      matrix:
        dart: ["2.3", "latest", "dev"]
    runs-on: ubuntu-latest
    container: google/dart:${{ matrix.dart }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: pub get --no-precompile
      - run: pub run dart_dev test --test-args="--shard-index=1 --total-shards=5"

  test3:
    name: Test (3/5)
    strategy:
      fail-fast: false
      matrix:
        dart: ["2.3", "latest", "dev"]
    runs-on: ubuntu-latest
    container: google/dart:${{ matrix.dart }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: pub get --no-precompile
      - run: pub run dart_dev test --test-args="--shard-index=2 --total-shards=5"

  test4:
    name: Test (4/5)
    strategy:
      fail-fast: false
      matrix:
        dart: ["2.3", "latest", "dev"]
    runs-on: ubuntu-latest
    container: google/dart:${{ matrix.dart }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: pub get --no-precompile
      - run: pub run dart_dev test --test-args="--shard-index=3 --total-shards=5"

  test5:
    name: Test (4/5)
    strategy:
      fail-fast: false
      matrix:
        dart: ["2.3", "latest", "dev"]
    runs-on: ubuntu-latest
    container: google/dart:${{ matrix.dart }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: pub get --no-precompile
      - run: pub run dart_dev test --test-args="--shard-index=4 --total-shards=5"
