name: CI

on: [push]

jobs:
  analyze:
    name: Analyze
    strategy:
      fail-fast: false
      matrix:
        dart: ["2.3", "latest", "dev"]
    runs-on: ubuntu-latest
    container: google/dart:${{ matrix.dart }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: pub get
      - name: Analyze
        run: pub run dart_dev analyze

  format:
    name: Format
    strategy:
      fail-fast: false
      matrix:
        dart: ["2.3", "latest", "dev"]
    runs-on: ubuntu-latest
    container: google/dart:${{ matrix.dart }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: pub get
      - name: Analyze
        run: pub run dart_dev format --check

  publish-dry-run:
    name: Publish Dry-Run
    strategy:
      fail-fast: false
      matrix:
        dart: ["2.3", "latest", "dev"]
    runs-on: ubuntu-latest
    container: google/dart:${{ matrix.dart }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: pub get
      - name: Analyze
        run: pub publish --dry-run

  validate-deps:
    name: Validate Deps
    strategy:
      fail-fast: false
      matrix:
        dart: ["2.3", "latest", "dev"]
    runs-on: ubuntu-latest
    container: google/dart:${{ matrix.dart }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: pub get
      - name: Analyze
        run: pub run dependency_validator -i pedantic

  test1:
    name: Test (1/4)
    name: Format
    strategy:
      fail-fast: false
      matrix:
        dart: ["2.3", "latest", "dev"]
    runs-on: ubuntu-latest
    container: google/dart:${{ matrix.dart }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: pub get
      - name: Analyze
        run: pub run dart_dev test --test-args="--shard-index=0 --total-shards=4"

  test2:
    name: Test (2/4)
    name: Format
    strategy:
      fail-fast: false
      matrix:
        dart: ["2.3", "latest", "dev"]
    runs-on: ubuntu-latest
    container: google/dart:${{ matrix.dart }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: pub get
      - name: Analyze
        run: pub run dart_dev test --test-args="--shard-index=1 --total-shards=4"

  test3:
    name: Test (3/4)
    name: Format
    strategy:
      fail-fast: false
      matrix:
        dart: ["2.3", "latest", "dev"]
    runs-on: ubuntu-latest
    container: google/dart:${{ matrix.dart }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: pub get
      - name: Analyze
        run: pub run dart_dev test --test-args="--shard-index=2 --total-shards=4"

  test4:
    name: Test (4/4)
    name: Format
    strategy:
      fail-fast: false
      matrix:
        dart: ["2.3", "latest", "dev"]
    runs-on: ubuntu-latest
    container: google/dart:${{ matrix.dart }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: pub get
      - name: Analyze
        run: pub run dart_dev test --test-args="--shard-index=3 --total-shards=4"
