name: CI

on:
  pull_request:
  push:
    branches:
      - 'master'

permissions:
  pull-requests: write
  contents: write
  id-token: write

jobs:
  build:
    uses: Workiva/gha-dart-oss/.github/workflows/build.yaml@v0.1.5

  checks:
    uses: Workiva/gha-dart-oss/.github/workflows/checks.yaml@v0.1.5

  test-unit:
    strategy:
      matrix:
        sdk: [ 2.19.6, stable ]
    uses: Workiva/gha-dart-oss/.github/workflows/test-unit.yaml@v0.1.5
    with:
      sdk: ${{ matrix.sdk }}