name: CI

on:
  pull_request:
  push:
    branches:
      - 'master'
      - 'test_consume_*'

permissions:
  pull-requests: write
  contents: write
  id-token: write

jobs:
  build:
    uses: Workiva/gha-dart-oss/.github/workflows/build.yaml@v0.1.5

  checks:
    uses: Workiva/gha-dart-oss/.github/workflows/checks.yaml@v0.1.5

  dart:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu, windows ]
        sdk: [ 2.19.6, stable ]
    name: Dart ${{ matrix.sdk }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install dependencies
        run: dart pub get
      - name: Tests
        run: dart run dart_dev test ${{ matrix.sdk != '2.19.6' && '--test-args="--exclude-tags dart2"' || '' }}