name: CI

on:
  push:
    branches:
      - 'master'
      - 'test_consume_*'
  pull_request:
    branches:
      - '**'

permissions:
  pull-requests: write
  contents: write
  id-token: write

jobs:
  dart:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu, windows ]
        sdk: [ 2.19.6, stable ]
    name: Dart ${{ matrix.sdk }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - run: |
          ACTIONS_ID_TOKEN_REQUEST_URL
          [ -z "$ACTIONS_ID_TOKEN_REQUEST_URL" ] && echo "ACTIONS_ID_TOKEN_REQUEST_URL is not set" || echo "ACTIONS_ID_TOKEN_REQUEST_URL is set"
          [ -z "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" ] && echo "ACTIONS_ID_TOKEN_REQUEST_TOKEN is not set" || echo "ACTIONS_ID_TOKEN_REQUEST_TOKEN is set"
      - uses: actions/checkout@v4
      - run: ls -la "$HOME/.config/dart" || echo "no dart config dir"
      - run: |
          [ -z "$PUB_TOKEN" ] && echo "PUB_TOKEN is not set" || echo "PUB_TOKEN is set"
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - run: ls -la "$HOME/.config/dart" || echo "no dart config dir"
      - run: dart pub token remove --all
      - name: Install dependencies
        run: dart pub get
      - name: Validate dependencies
        run: dart run dependency_validator
      - name: Analysis
        run: dart run dart_dev analyze
      - name: Formatting
        if: ${{ matrix.sdk == 'stable' && matrix.os == 'ubuntu' }}
        run: dart run dart_dev format --check
      - name: Tests
        run: dart run dart_dev test ${{ matrix.sdk != '2.19.6' && '--test-args="--exclude-tags dart2"' || '' }}
      - name: SBOM
        if: ${{ matrix.sdk == '2.19.6' && matrix.os == 'ubuntu' }}
        uses: anchore/sbom-action@v0
        with:
          path: ./  # Assuming actions/checkout default location
          format: cyclonedx-json
