name: Dart CI

on:
  push:
    branches:
      - 'master'
      - 'test_consume_*'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [ 2.18.7 ] # TODO: re-add stable when compatible
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - run: dart pub get
      - run: dart run dependency_validator
      - run: dart run dart_dev analyze
      - run: dart run dart_dev test

  format_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.18.7
      - run: dart pub get
      - run: dart run dart_dev format --check
      # TODO: uncomment once https://github.com/dart-lang/sdk/issues/51398 is fixed
      # - run: dart pub publish --dry-run

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.18.7

      - id: install
        name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart run dart_dev test
        if: always() && steps.install.outcome == 'success'
